modLoader="javafml"
loaderVersion="[28,)"
[[mods]]
modId="arcanemechina"
version="0.1.1.13"
displayName="Arcane Mechina"
logoFile="logo.png"
description='''
a mod with a mix of arcane and mechanical features!
'''
authors="on Twitter: @NadirRift and @SNReloaded"